import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";
import { MetaMaskInpageProvider } from "@metamask/providers";
import { Maybe } from "@metamask/providers/dist/utils";

declare global {
  interface Window {
    ethereum: MetaMaskInpageProvider;
  }
}

const Home: NextPage = () => {
  const [currentAccount, setCurrentAccount] = useState("");

  const ethereumExists = () => {};

  const checkIfWalletIsConnected = async () => {
    try {
      /*
       * First make sure we have access to window.ethereum
       */
      if (typeof window === "undefined") {
        return;
      }
      const { ethereum } = window;
      if (!ethereum) {
        return;
      }

      /*
       * Check if we're authorized to access the user's wallet
       */
      const accounts: Maybe<string[]> = await ethereum.request({
        method: "eth_accounts",
      });
      if (accounts == undefined || accounts == null) {
        return;
      }
      if (accounts.length > 0) {
        const account: string | undefined = accounts[0];
        if (account === undefined) {
          return;
        }
        console.log("Found an authorized account:", account);
        setCurrentAccount(account);
      } else {
        console.log("No authorized account found");
      }
    } catch (error) {
      console.log(error);
    }
  };
  /**
   * Implement your connectWallet method here
   */
  const connectWallet = async () => {
    try {
      const { ethereum } = window;

      if (!ethereum) {
        alert("Get MetaMask!");
        return;
      }

      const accounts: Maybe<string[]> = await ethereum.request({
        method: "eth_requestAccounts",
      });
      if (accounts == undefined || accounts == null) {
        return;
      }
      const account: string | undefined = accounts[0];
      if (account === undefined) {
        return;
      }
      console.log("Connected", account);
      setCurrentAccount(account);
    } catch (error) {
      console.log(error);
    }
  };

  /*
   * This runs our function when the page loads.
   */
  useEffect(() => {
    checkIfWalletIsConnected();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="mainContainer">
          <div className="dataContainer">
            <div className="header">👋 Hey there!</div>

            <div className="bio">Test bio</div>

            <button className="waveButton">Wave at Me</button>
          </div>
          {/*
           * If there is no currentAccount render this button
           */}
          {!currentAccount && (
            <button className="waveButton" onClick={connectWallet}>
              Connect Wallet
            </button>
          )}
        </div>
      </main>
    </div>
  );
};

export default Home;
